### ISSUE TITLE
Compile failure w/ GHC 7.10.3 & GHC 7.8.4

### ISSUE THREAD

**Issue by hvr** [rlupton20/tyro#1]
Hi,

I noticed the following compile error for with GHC 7.10.3 (and something similiar w/ GHC 7.8.4):

```
Configuring component lib from tyro-0.1.1.0...
Preprocessing library tyro-0.1.1.0...

src/Data/Tyro.hs:12:16:
    unknown flag in  {-# OPTIONS_GHC #-} pragma: -fno-warn-redundant-constraints
```

(see also http://104.239.175.197:8080/package/tyro#GHC-7.8/tyro-0.1.1.0 )

**Comment by rlupton20** [comment]
Thanks for letting me know!

The pragma is there to suppress warnings that GHC raises for constraints it doesn't think it needs to be there, but actually do (a somewhat annoying side effect of using `singletons` in some situations).

I have a dependency on the `singletons` library, so (from their docs), need GHC 8+ anyway - I'll fix the version restriction of `base` in the cabal file so it won't build against earlier versions, and push a new version to hackage. Apologies, this was a little careless of me!

**Comment by hvr** [comment]
Great! Fyi, I've revised the meta-data for the previous release as well at https://hackage.haskell.org/package/tyro-0.1.1.0/revisions/ (as otherwise `cabal`'s solver would just back-track to the previous version which has more lax constraints).

For the future, here's where you can revise meta-data yourself: https://hackage.haskell.org/package/tyro-0.1.1.1/tyro.cabal/edit - If you have any questions, please ask! :-)

**Comment by rlupton20** [comment]
Perfect, thanks for doing that, and pointing me in the right directions. I'm new to hackage, so this is definitely useful!

I'll close this now, but don't hesitate to prod me if I've done something else daft :-) .
